# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e26c2c9e431cc0bec836c985a37cd5df98fd592c4ba9a088825897f78145474e8678e9e88c6d4e2a4ba318290d3e1fda79da59de5cab613c53ce98f946af6177

test:
  secret_key_base: c5b117cc4bf59c7a99f40c0efc00d036501d905b6fea51f10b91c35430bcda07610070e39f4fdbc3213451dc4a11e9c8b6bcdb8c11c4de0bd6a45c7ab1dc3ab8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
